### ISSUE TITLE
Better Storage plug-in Crash 

### ISSUE THREAD

**Issue by Xhamolk** [Xhamolk/XACT#86]
```
java.lang.IllegalStateException: Can't be called client-side.
at net.mcft.copy.betterstorage.block.crate.TileEntityCrate.getPileData(TileEntityCrate.java:39)
at net.mcft.copy.betterstorage.block.crate.TileEntityCrate.getContents(TileEntityCrate.java:270)
at xk.xact.plugin.betterstorage.inventory.CrateInventory.iterator(CrateInventory.java:41)
at xk.xact.api.CraftingHandler.getCountFor(CraftingHandler.java:223)
at xk.xact.api.CraftingHandler.canCraft(CraftingHandler.java:70)
at xk.xact.api.CraftingHandler.generateTemporaryCraftingGridFor(CraftingHandler.java:244)
at xk.xact.api.CraftingHandler.doCraft(CraftingHandler.java:78)
at xk.xact.gui.SlotCraft.func_82870_a(SlotCraft.java:81)
at xk.xact.gui.ContainerXACT.func_75144_a(ContainerXACT.java:249)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:473)
at net.minecraft.client.gui.inventory.GuiContainer.func_74191_a(GuiContainer.java:886)
at net.minecraft.client.gui.inventory.GuiContainer.func_73879_b(GuiContainer.java:838)
at net.minecraft.client.gui.GuiScreen.func_73867_d(SourceFile:132)
at net.minecraft.client.gui.inventory.GuiContainer.func_73867_d(GuiContainer.java:1009)
at xk.xact.client.gui.GuiXACT.func_73867_d(GuiXACT.java:31)
at net.minecraft.client.gui.GuiScreen.func_73862_m(SourceFile:107)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1554)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:898)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:826)
at net.minecraft.client.main.Main.main(SourceFile:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
```

**Comment by Xhamolk** [comment]
Unable to reproduce...
